project:
  type: website

website:
  title: "DFA Blog"
  navbar:
    right:
      - icon: globe
        href: https://www.dfa.ns.ca/
      - icon: facebook
        href: https://www.facebook.com/dalfacultyassoc/
      - icon: twitter
        href: https://twitter.com/dalfacultyassoc
      - icon: instagram
        href: https://www.instagram.com/dalfacultyassoc/?hl=en
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

